# Generated by Django 3.2.4 on 2021-06-29 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_classmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('role', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=255)),
                ('wechat', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=255)),
                ('onecard', models.ImageField(upload_to='uploads/')),
                ('classes', models.ManyToManyField(to='courses.ClassModel')),
            ],
            options={
                'db_table': 'users_user',
                'ordering': ('name',),
            },
        ),
    ]
